create table if not exists businesses (
 id bigint generated by default as identity primary key,
 name text not null,
 category text not null,
 city text not null default 'Turgutlu',
 description text,
 phone text,
 featured boolean default false,
 views integer default 0,
 owner_id uuid,
 created_at timestamptz default now()
);
alter table businesses enable row level security;
create policy "public read businesses" on businesses for select using (true);
create policy "authenticated insert businesses" on businesses for insert to authenticated with check (auth.uid() = owner_id);
create policy "owner update businesses" on businesses for update to authenticated using (auth.uid() = owner_id);